ARG APP_PATH=/opt/outline

FROM node:26.3.0 AS build

ARG APP_PATH
WORKDIR $APP_PATH

COPY ./package.json ./yarn.lock ./.yarnrc.yml ./
COPY ./patches ./patches

RUN apt-get update \
  && apt-get install -y --no-install-recommends cmake \
  && rm -rf /var/lib/apt/lists/*

ENV NODE_OPTIONS="--max-old-space-size=24000"

RUN npm install -g corepack \
  && corepack enable

RUN yarn install --immutable --network-timeout 1000000 \
  && yarn cache clean

COPY . .

ARG CDN_URL
RUN yarn build

RUN yarn workspaces focus --production \
  && yarn cache clean

FROM node:26.3.0-slim AS runner

ARG APP_PATH
WORKDIR $APP_PATH

LABEL org.opencontainers.image.source="https://github.com/23fo/outline"

ENV NODE_ENV=production
ENV MALLOC_ARENA_MAX=2
ENV FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data

RUN addgroup --gid 1001 nodejs \
  && adduser --uid 1001 --ingroup nodejs nodejs \
  && mkdir -p /var/lib/outline/data \
  && chown -R nodejs:nodejs /var/lib/outline \
  && chown -R nodejs:nodejs $APP_PATH \
  && chmod 1777 /var/lib/outline/data \
  && apt-get update \
  && apt-get install -y --no-install-recommends wget \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build --chown=nodejs:nodejs $APP_PATH/build ./build
COPY --from=build --chown=nodejs:nodejs $APP_PATH/server ./server
COPY --from=build --chown=nodejs:nodejs $APP_PATH/public ./public
COPY --from=build --chown=nodejs:nodejs $APP_PATH/.sequelizerc ./.sequelizerc
COPY --from=build --chown=nodejs:nodejs $APP_PATH/node_modules ./node_modules
COPY --from=build --chown=nodejs:nodejs $APP_PATH/package.json ./package.json

VOLUME /var/lib/outline/data

USER nodejs

HEALTHCHECK --interval=1m CMD wget -qO- "http://localhost:${PORT:-3000}/_health" | grep -q "OK" || exit 1

EXPOSE 3000
CMD ["node", "build/server/index.js"]
